## Numpy의 indexing


In [0]:
# 우선 실행해 주세요
import numpy as np

#### 예제) 

* 중간고사, 학생들의 국영수사과 성적표

| 학생 번호 | 국어 | 영어 | 수학 | 사회 | 과학 |
|  ----   | --- |---| --- | --- | --- |
|0 |80 |92 |70 | 65 | 92 |
|1 |91 |75 |90 | 68 | 85 | 
|2 |86 |76 |42 | 72 | 88 |
|3 |77 |92 |52 | 60 | 80 |
|4 |75 |85 |85 | 92 | 95 |
|5 |96 |90 |95 | 81 | 72 |


* 기말고사, 학생들의 국영수사과 성적표

| 학생 번호 | 국어 | 영어 | 수학 | 사회 | 과학 |
|  ----   | --- |---| --- | --- | --- |
|0 |85 |95 |90 | 66 | 93 |
|1 |93 |70 |80 | 60 | 81 | 
|2 |89 |78 |55 | 75 | 80 |
|3 |80 |94 |59 | 72 | 90 |
|4 |70 |82 |81 | 95 | 72 |
|5 |90 |76 |93 | 82 | 89 |

In [0]:
middle_scores = np.array([
    [80,92,70,65,92],
    [91,75,90,68,85],
    [86,76,42,72,88],
    [77,92,52,60,80],
    [75,85,85,92,95],
    [96,90,95,81,72]
])

final_scores = np.array([
    [85,95,90,66,93],
    [93,70,80,60,81],
    [89,78,55,75,80],
    [80,94,59,72,90],
    [70,82,81,95,72],
    [90,76,93,82,89]
])

scores = np.stack([middle_scores, final_scores])
scores

array([[[80, 92, 70, 65, 92],
        [91, 75, 90, 68, 85],
        [86, 76, 42, 72, 88],
        [77, 92, 52, 60, 80],
        [75, 85, 85, 92, 95],
        [96, 90, 95, 81, 72]],

       [[85, 95, 90, 66, 93],
        [93, 70, 80, 60, 81],
        [89, 78, 55, 75, 80],
        [80, 94, 59, 72, 90],
        [70, 82, 81, 95, 72],
        [90, 76, 93, 82, 89]]])

현재 데이터의 shape는 (2,6,5)로, 

* 첫번째 축 : 중간 / 기말
* 두번째 축 : 학생 번호 
* 세번째 축 : 과목

으로 구성되어 있다.

## 문제 1. 배열 원소 Indexing 하기
* 학생 3번의 중간고사 사회 성적을 가져와 주세요

정답 >>> 60

In [0]:
# 우선 실행해주세요
scores = np.stack([middle_scores, final_scores])
scores

array([[[80, 92, 70, 65, 92],
        [91, 75, 90, 68, 85],
        [86, 76, 42, 72, 88],
        [77, 92, 52, 60, 80],
        [75, 85, 85, 92, 95],
        [96, 90, 95, 81, 72]],

       [[85, 95, 90, 66, 93],
        [93, 70, 80, 60, 81],
        [89, 78, 55, 75, 80],
        [80, 94, 59, 72, 90],
        [70, 82, 81, 95, 72],
        [90, 76, 93, 82, 89]]])

#### 답안지 입력란
* 아래에 답을 서술하여 주세요
* 결과는 `answer1`에 담아주세요

In [0]:
answer1 = scores[0,3,3]

In [0]:
answer1

60

#### 정답 확인
* 정답을 입력한 후, 아래를 실행시키면 정답인지 확인합니다.

In [0]:
from numpy.testing import assert_array_equal

assert 'answer1' in globals(), "결과를 answer1 변수에 담아주세요!, answer1 값을 보고 평가합니다."

A = 60

assert_array_equal(A, answer1, 
               err_msg="\n정답은 \n{}\n입니다. 다시 확인해 주세요\n".format(A))

print("정답입니다!!!")

정답입니다!!!


## 문제 2. 배열 특정 범위 가져오기
* 학생 2번부터 4번까지의 기말고사 국어,영어,수학 성적을 가져와 주세요

정답 >>> 60

In [0]:
# 우선 실행해주세요
scores = np.stack([middle_scores, final_scores])
scores

array([[[80, 92, 70, 65, 92],
        [91, 75, 90, 68, 85],
        [86, 76, 42, 72, 88],
        [77, 92, 52, 60, 80],
        [75, 85, 85, 92, 95],
        [96, 90, 95, 81, 72]],

       [[85, 95, 90, 66, 93],
        [93, 70, 80, 60, 81],
        [89, 78, 55, 75, 80],
        [80, 94, 59, 72, 90],
        [70, 82, 81, 95, 72],
        [90, 76, 93, 82, 89]]])

#### 답안지 입력란
* 아래에 답을 서술하여 주세요
* 결과는 `answer2`에 담아주세요

In [0]:
answer2 = scores[1,2:5,:3]

#### 정답 확인
* 정답을 입력한 후, 아래를 실행시키면 정답인지 확인합니다.

In [0]:
from numpy.testing import assert_array_equal

assert 'answer2' in globals(), "결과를 answer2 변수에 담아주세요!, answer2 값을 보고 평가합니다."

A = [[89, 78, 55],
     [80, 94, 59],
     [70, 82, 81]]

assert_array_equal(A, answer2,"\n\n정답은 \n{}\n입니다. 다시 확인해 주세요".format(A))
print("정답입니다!!!")

정답입니다!!!


## 문제 3. 조건문으로 가져오기
* 중간고사, 기말고사 통틀어, 한번이라도 **수학 성적이 90과 같거나 큰 학생**들의 전 과목 성적을 가져와 주세요

정답 >>> [[91, 75, 90, 68, 85],
[96, 90, 95, 81, 72],
[85, 95, 90, 66, 93],
[90, 76, 93, 82, 89]]

의 형태로 나와야 합니다.

In [0]:
# 우선 실행해주세요
scores = np.stack([middle_scores, final_scores])
scores

array([[[80, 92, 70, 65, 92],
        [91, 75, 90, 68, 85],
        [86, 76, 42, 72, 88],
        [77, 92, 52, 60, 80],
        [75, 85, 85, 92, 95],
        [96, 90, 95, 81, 72]],

       [[85, 95, 90, 66, 93],
        [93, 70, 80, 60, 81],
        [89, 78, 55, 75, 80],
        [80, 94, 59, 72, 90],
        [70, 82, 81, 95, 72],
        [90, 76, 93, 82, 89]]])

#### 답안지 입력란
* 아래에 답을 서술하여 주세요
* 결과는 `answer3`에 담아주세요

In [0]:
over_90 = scores[:,:,2]>=90

answer3 = scores[over_90]
answer3

array([[91, 75, 90, 68, 85],
       [96, 90, 95, 81, 72],
       [85, 95, 90, 66, 93],
       [90, 76, 93, 82, 89]])

#### 정답 확인
* 정답을 입력한 후, 아래를 실행시키면 정답인지 확인합니다.

In [0]:
from numpy.testing import assert_array_equal

assert 'answer3' in globals(), "결과를 answer3 변수에 담아주세요!, answer3 값을 보고 평가합니다."

A = np.array([[91, 75, 90, 68, 85],
              [96, 90, 95, 81, 72],
              [85, 95, 90, 66, 93],
              [90, 76, 93, 82, 89]])

assert_array_equal(A,answer3,
                   err_msg="\n\n정답은 \n{}\n입니다. 다시 확인해 주세요".format(A))

print("정답입니다!!!")

정답입니다!!!


## 문제 4. 새로운 데이터 추가하기
* 새로운 학생(6번)의 성적을 추가하여 주세요

* 중간 고사 성적

|학생번호|국어|영어|수학|사회|과학|
|---|---|---|---|---|---|
|6|90|82|85|83|81|

* 기말 고사 성적

|학생번호|국어|영어|수학|사회|과학|
|---|---|---|---|---|---|
|6|95|83|81|85|83|

In [0]:
# 우선 실행해주세요
scores = np.stack([middle_scores, final_scores])
scores

array([[[80, 92, 70, 65, 92],
        [91, 75, 90, 68, 85],
        [86, 76, 42, 72, 88],
        [77, 92, 52, 60, 80],
        [75, 85, 85, 92, 95],
        [96, 90, 95, 81, 72]],

       [[85, 95, 90, 66, 93],
        [93, 70, 80, 60, 81],
        [89, 78, 55, 75, 80],
        [80, 94, 59, 72, 90],
        [70, 82, 81, 95, 72],
        [90, 76, 93, 82, 89]]])

In [0]:
new_middle_score = np.array([90,82,85,83,81])
new_final_score = np.array([95,83,81,85,83])

#### 답안지 입력란
* 아래에 답을 서술하여 주세요
* 결과는 `answer4`에 담아주세요

In [0]:
new_score = np.stack([new_middle_score,new_final_score])
new_score = new_score.reshape(2,1,5)

answer4 = np.concatenate([scores,new_score],axis=1)

#### 정답 확인
* 정답을 입력한 후, 아래를 실행시키면 정답인지 확인합니다.

In [0]:
from numpy.testing import assert_array_almost_equal

assert 'answer4' in globals(), "결과를 answer4 변수에 담아주세요!, answer4 값을 보고 평가합니다."

A = [[[80, 92, 70, 65, 92],
        [91, 75, 90, 68, 85],
        [86, 76, 42, 72, 88],
        [77, 92, 52, 60, 80],
        [75, 85, 85, 92, 95],
        [96, 90, 95, 81, 72],
        [90, 82, 85, 83, 81]],

       [[85, 95, 90, 66, 93],
        [93, 70, 80, 60, 81],
        [89, 78, 55, 75, 80],
        [80, 94, 59, 72, 90],
        [70, 82, 81, 95, 72],
        [90, 76, 93, 82, 89],
        [95, 83, 81, 85, 83]]]

assert_array_almost_equal(A,answer4,decimal=2,
                          err_msg="\n\n정답은 \n{}\n입니다. 다시 확인해 주세요".format(A))

print("정답입니다!!!")

정답입니다!!!
